CREATE TABLE QUESTIONARY_ANSWER_TYPE
(ID			NUMBER, 
NAME		VARCHAR2(100) NOT NULL);

ALTER TABLE QUESTIONARY_ANSWER_TYPE ADD CONSTRAINT QUESTIONARY_ANSWER_TYPE_PK PRIMARY KEY (ID);
ALTER TABLE QUESTIONARY_ANSWER_TYPE ADD CONSTRAINT QUESTIONARY_ANSWER_TYPE_UK UNIQUE (NAME);

CREATE SEQUENCE SEQ_QUESTIONARY_ANSWER_TYPE
	START WITH 1
	INCREMENT BY 1
		NOCACHE
		NOCYCLE;

CREATE TRIGGER TRG_QUESTIONARY_ANSWER_TYPE_I_U
	BEFORE UPDATE OR INSERT
		ON QUESTIONARY_ANSWER_TYPE
	FOR EACH ROW
BEGIN
    IF(INSERTING) THEN
		:NEW.ID := SEQ_QUESTIONARY_ANSWER_TYPE.NEXTVAL;
    END IF;
   
    IF(UPDATING) THEN
		IF :NEW.ID <> :OLD.ID THEN 
			raise_application_error(-20555, 'Can`t change id');
		END IF;
    END IF; 
END;
/

CREATE VIEW V_QUESTIONARY_ANSWER_TYPE
	(ID, 
	NAME)
AS 
SELECT ID, 
       NAME 
	FROM QUESTIONARY_ANSWER_TYPE;