INSERT INTO QUESTIONARY_ANSWER_TYPE(NAME) VALUES ('String');

INSERT INTO QUESTIONARY_ANSWER_TYPE(NAME) VALUES ('Number');

INSERT INTO QUESTIONARY_ANSWER_TYPE(NAME) VALUES ('Date');

INSERT INTO QUESTIONARY_ANSWER_TYPE(NAME) VALUES ('Blob');