CREATE TABLE QUESTIONARY_QUESTION
(ID				NUMBER,
TEMPLATE_ID		NUMBER			NOT NULL,
QUESTION		VARCHAR2(4000)	NOT NULL,
ANSWER_TYPE_ID	NUMBER			NOT NULL);

ALTER TABLE QUESTIONARY_QUESTION ADD CONSTRAINT QUESTIONARY_QUESTION_PK PRIMARY KEY (ID);

ALTER TABLE QUESTIONARY_QUESTION ADD CONSTRAINT QUESTIONARY_QUESTION_TEMPLATE_FK FOREIGN KEY (TEMPLATE_ID) REFERENCES QUESTIONARY_TEMPLATE (ID);

ALTER TABLE QUESTIONARY_QUESTION ADD CONSTRAINT QUESTIONARY_QUESTION_ANSW_TYPE_FK FOREIGN KEY (ANSWER_TYPE_ID) REFERENCES QUESTIONARY_ANSWER_TYPE (ID);

CREATE SEQUENCE SEQ_QUESTIONARY_QUESTION
	START WITH 1
	INCREMENT BY 1
		NOCACHE
		NOCYCLE;

CREATE TRIGGER TRG_QUESTIONARY_QUESTION_I_U
	BEFORE UPDATE OR INSERT
		ON QUESTIONARY_QUESTION
	FOR EACH ROW
BEGIN
    IF(INSERTING) THEN
		:NEW.ID := SEQ_QUESTIONARY_QUESTION.NEXTVAL;
    END IF;
   
    IF(UPDATING) THEN
		IF :NEW.ID <> :OLD.ID THEN 
			raise_application_error(-20555, 'Can`t change id');
		END IF;
    END IF; 
END;
/

CREATE VIEW V_QUESTIONARY_QUESTION
	(ID, 
	TEMPLATE_ID, 
	TEMPLATE_NAME, 
	QUESTION, 
	ANSWER_TYPE_ID, 
	ANSWER_TYPE)
AS 
SELECT q.ID, 
	   q.TEMPLATE_ID,
	   t.NAME AS TEMPLATE_NAME,
	   q.QUESTION,
	   q.ANSWER_TYPE_ID,
	   ans_t.NAME AS ANSWER_TYPE
	FROM QUESTIONARY_QUESTION q 
	INNER JOIN QUESTIONARY_TEMPLATE t 
		ON q.TEMPLATE_ID = t.ID
	INNER JOIN QUESTIONARY_ANSWER_TYPE ans_t 
		ON q.ANSWER_TYPE_ID = ans_t.ID;