CREATE TABLE QUESTIONARY 
(ID 			NUMBER, 
 TEMPLATE_ID 	NUMBER	NOT NULL,
 DATE_BEG 		DATE 	NOT NULL,
 DATE_END 		DATE);
 
ALTER TABLE QUESTIONARY ADD CONSTRAINT QUESTIONARY_PK PRIMARY KEY (ID);

ALTER TABLE QUESTIONARY ADD CONSTRAINT QUESTIONARY_TEMPLATE_FK FOREIGN KEY (TEMPLATE_ID) REFERENCES QUESTIONARY_TEMPLATE (ID);

CREATE SEQUENCE SEQ_QUESTIONARY
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE TRIGGER TRG_QUESTIONARY_I_U
	BEFORE UPDATE OR INSERT
		ON QUESTIONARY
	FOR EACH ROW
BEGIN
    IF(INSERTING) THEN
		:NEW.ID := SEQ_QUESTIONARY.NEXTVAL;
    END IF;
   
    IF(UPDATING) THEN
		IF :NEW.ID <> :OLD.ID THEN 
			raise_application_error(-20555, 'Can`t change id');
		END IF;
    END IF; 
END;
/