CREATE TABLE QUESTIONARY_USERS
(ID 			NUMBER, 
USER_ID 		NUMBER 		NOT NULL, 
QUESTIONARY_ID 	NUMBER 		NOT NULL);

ALTER TABLE QUESTIONARY_USERS ADD CONSTRAINT QUESTIONARY_USERS_PK PRIMARY KEY (ID);

ALTER TABLE QUESTIONARY_USERS ADD CONSTRAINT QUESTIONARY_USERS_Q_FK FOREIGN KEY (QUESTIONARY_ID) REFERENCES QUESTIONARY (ID);