CREATE OR REPLACE PACKAGE BODY PKG$QUESTIONARY
AS

-- Create Questionary Template
PROCEDURE pCREATE_QUESTIONARY_TEMPLATE(P_vNAME IN VARCHAR2)
IS
BEGIN
	INSERT INTO QUESTIONARY_TEMPLATE
				(NAME)
		VALUES (P_vNAME);
END pCREATE_QUESTIONARY_TEMPLATE;

-- Update Questionary Template
PROCEDURE pUPDATE_QUESTIONARY_TEMPLATE(P_nID 	IN NUMBER,
										P_vNAME IN VARCHAR2)
IS 
BEGIN
	UPDATE QUESTIONARY_TEMPLATE 
		SET NAME = P_vNAME
		WHERE ID = P_nID;
END pUPDATE_QUESTIONARY_TEMPLATE;

-- Delete Questionary Template
PROCEDURE pDELETE_QUESTIONARY_TEMPLATE(P_nID IN NUMBER)
IS
BEGIN
	DELETE 
		FROM QUESTIONARY_TEMPLATE
		WHERE ID = P_nID;
END pDELETE_QUESTIONARY_TEMPLATE;

-- Create Questionary Answer Type
PROCEDURE pCREATE_Q_ANSWER_TYPE(P_vNAME IN VARCHAR2)
IS
BEGIN
	INSERT INTO QUESTIONARY_ANSWER_TYPE
				(NAME)
		VALUES (P_vNAME);
END pCREATE_Q_ANSWER_TYPE;

-- Update Questionary Answer Type
PROCEDURE pUPDATE_Q_ANSWER_TYPE(P_nID 	IN NUMBER,
								P_vNAME IN VARCHAR2)
IS 
BEGIN
	UPDATE QUESTIONARY_ANSWER_TYPE 
		SET NAME = P_vNAME
		WHERE ID = P_nID;
END pUPDATE_Q_ANSWER_TYPE;

-- Delete Questionary Answer Type
PROCEDURE pDELETE_Q_ANSWER_TYPE(P_nID IN NUMBER)
IS
BEGIN
	DELETE 
		FROM QUESTIONARY_ANSWER_TYPE
		WHERE ID = P_nID;
END pDELETE_Q_ANSWER_TYPE;

END PKG$QUESTIONARY;