CREATE OR REPLACE PACKAGE PKG_QUESTIONARY
AS

-- Create Questionary Template
PROCEDURE pCREATE_QUESTIONARY_TEMPLATE(P_vTEMPLATE_NAME IN VARCHAR2);

-- Update Questionary Template
PROCEDURE pUPDATE_QUESTIONARY_TEMPLATE(P_nID				IN NUMBER,
										P_vTEMPLATE_NAME	IN VARCHAR2);

-- Delete Questionary Template
PROCEDURE pDELETE_QUESTIONARY_TEMPLATE(P_nID IN NUMBER);

-- Create Questionary Answer Type
PROCEDURE pCREATE_Q_ANSWER_TYPE(P_vANSWER_TYPE IN VARCHAR2);

-- Update Questionary Answer Type
PROCEDURE pUPDATE_Q_ANSWER_TYPE(P_nID			IN NUMBER,
								P_vANSWER_TYPE	IN VARCHAR2);
 
-- Delete Questionary Answer Type
PROCEDURE pDELETE_Q_ANSWER_TYPE(P_nID IN NUMBER);

-- Create Questionary Question
PROCEDURE pCREATE_Q_QUESTION(P_nTEMPLATE_ID		IN NUMBER,
							P_vQUESTION			IN VARCHAR2,
							P_nANSWER_TYPE_ID	IN NUMBER);

-- Update Questionary Question
PROCEDURE pUPDATE_Q_QUESTION(P_nID				IN NUMBER,
							P_nTEMPLATE_ID		IN NUMBER,
							P_vQUESTION		IN VARCHAR2,
							P_nANSWER_TYPE_ID	IN NUMBER);

-- Delete Questionary Question
PROCEDURE pDELETE_Q_QUESTION(P_nID IN NUMBER);

-- Create Questionary
PROCEDURE pCREATE_Q_QUESTIONARY(P_nTEMPLATE_ID	IN NUMBER,
								P_dDATE_BEG		IN DATE,
								P_dDATE_END		IN DATE DEFAULT NULL);

-- Update Questionary
PROCEDURE pUPDATE_Q_QUESTIONARY(P_nID			IN NUMBER,
								P_nTEMPLATE_ID	IN NUMBER,
								P_dDATE_BEG		IN DATE,
								P_dDATE_END		IN DATE DEFAULT NULL);

-- Delete Questionary
PROCEDURE pDELETE_Q_QUESTIONARY(P_nID IN NUMBER);

-- Create Questionary User
PROCEDURE pCREATE_Q_USER(P_nUSER_ID			IN NUMBER,
						P_nQUESTIONARY_ID	IN NUMBER);

-- Update Questionary User
PROCEDURE pUPDATE_Q_USER(P_nID				IN NUMBER,
						P_nUSER_ID			IN NUMBER,
						P_nQUESTIONARY_ID	IN NUMBER);

-- Delete Questionary User
PROCEDURE pDELETE_Q_USER(P_nID IN NUMBER);

-- Create Questionary Answer
PROCEDURE pCREATE_Q_ANSWER(P_nQ_USER_ID		IN NUMBER,
							P_nQUESTION_ID		IN NUMBER,
							P_SANSWER			IN VARCHAR2 DEFAULT NULL,
							P_nANSWER			IN NUMBER DEFAULT NULL,
							P_DANSWER			IN DATE DEFAULT NULL,
							P_BANSWER			IN BLOB DEFAULT NULL,
							P_CANSWER			IN BLOB DEFAULT NULL);

-- Update Questionary Answer
PROCEDURE pUPDATE_Q_ANSWER(	P_nID				IN NUMBER,
							P_nQ_USER_ID		IN NUMBER,
							P_nQUESTION_ID		IN NUMBER,
							P_SANSWER			IN VARCHAR2 DEFAULT NULL,
							P_nANSWER			IN NUMBER DEFAULT NULL,
							P_DANSWER			IN DATE DEFAULT NULL,
							P_BANSWER			IN BLOB DEFAULT NULL,
							P_CANSWER			IN BLOB DEFAULT NULL);

-- Delete Questionary Answer
PROCEDURE pDELETE_Q_ANSWER(P_nID IN NUMBER);

END PKG_QUESTIONARY;