CREATE OR REPLACE PACKAGE BODY PKG_QUESTIONARY
AS

-- Create Questionary Template
PROCEDURE pCREATE_QUESTIONARY_TEMPLATE(P_vNAME IN VARCHAR2)
IS
BEGIN
	INSERT INTO QUESTIONARY_TEMPLATE
				(NAME)
		VALUES (P_vNAME);
END pCREATE_QUESTIONARY_TEMPLATE;

-- Update Questionary Template
PROCEDURE pUPDATE_QUESTIONARY_TEMPLATE(P_nID 	IN NUMBER,
										P_vNAME IN VARCHAR2)
IS
BEGIN
	UPDATE QUESTIONARY_TEMPLATE
		SET NAME = P_vNAME
		WHERE ID = P_nID;
END pUPDATE_QUESTIONARY_TEMPLATE;

-- Delete Questionary Template
PROCEDURE pDELETE_QUESTIONARY_TEMPLATE(P_nID IN NUMBER)
IS
BEGIN
	DELETE 
		FROM QUESTIONARY_TEMPLATE
		WHERE ID = P_nID;
END pDELETE_QUESTIONARY_TEMPLATE;

-- Create Questionary Answer Type
PROCEDURE pCREATE_Q_ANSWER_TYPE(P_vNAME IN VARCHAR2)
IS
BEGIN
	INSERT INTO QUESTIONARY_ANSWER_TYPE
				(NAME)
		VALUES (P_vNAME);
END pCREATE_Q_ANSWER_TYPE;

-- Update Questionary Answer Type
PROCEDURE pUPDATE_Q_ANSWER_TYPE(P_nID 	IN NUMBER,
								P_vNAME IN VARCHAR2)
IS
BEGIN
	UPDATE QUESTIONARY_ANSWER_TYPE
		SET NAME = P_vNAME
		WHERE ID = P_nID;
END pUPDATE_Q_ANSWER_TYPE;

-- Delete Questionary Answer Type
PROCEDURE pDELETE_Q_ANSWER_TYPE(P_nID IN NUMBER)
IS
BEGIN
	DELETE 
		FROM QUESTIONARY_ANSWER_TYPE
		WHERE ID = P_nID;
END pDELETE_Q_ANSWER_TYPE;

-- Create Questionary Question
PROCEDURE pCREATE_Q_QUESTION(P_nTEMPLATE_ID 	IN NUMBER,
							P_vQUESTION 		IN VARCHAR2,
							P_nANSWER_TYPE_ID	IN NUMBER)
IS
BEGIN
	INSERT INTO QUESTIONARY_QUESTION
				(TEMPLATE_ID,
				QUESTION,
				ANSWER_TYPE_ID)
		VALUES (P_nTEMPLATE_ID,
				P_vQUESTION,
				P_nANSWER_TYPE_ID);
END pCREATE_Q_QUESTION;

-- Update Questionary Question
PROCEDURE pUPDATE_Q_QUESTION(P_nID 				IN NUMBER,
							P_nTEMPLATE_ID 		IN NUMBER,
							P_vQUESTION 		IN VARCHAR2,
							P_nANSWER_TYPE_ID	IN NUMBER)
IS
BEGIN
	UPDATE QUESTIONARY_QUESTION
		SET TEMPLATE_ID = P_nTEMPLATE_ID,
			QUESTION = P_vQUESTION,
			ANSWER_TYPE_ID = P_nANSWER_TYPE_ID
		WHERE ID = P_nID;
END pUPDATE_Q_QUESTION;

-- Delete Questionary Question
PROCEDURE pDELETE_Q_QUESTION(P_nID IN NUMBER)
IS
BEGIN
	DELETE
		FROM QUESTIONARY_QUESTION
		WHERE ID = P_nID;
END pDELETE_Q_QUESTION;

-- Create Questionary
PROCEDURE pCREATE_Q_QUESTIONARY(P_nTEMPLATE_ID 	IN NUMBER,
								P_dDATE_BEG 	IN DATE,
								P_dDATE_END		IN DATE DEFAULT NULL)
IS
BEGIN
	INSERT INTO QUESTIONARY
				(TEMPLATE_ID,
				DATE_BEG,
				DATE_END)
		VALUES (P_nTEMPLATE_ID,
				P_dDATE_BEG,
				P_dDATE_END);
END pCREATE_Q_QUESTIONARY;

-- Update Questionary
PROCEDURE pUPDATE_Q_QUESTIONARY(P_nID 			IN NUMBER,
								P_nTEMPLATE_ID 	IN NUMBER,
								P_dDATE_BEG 	IN DATE,
								P_dDATE_END		IN DATE DEFAULT NULL)
IS
BEGIN
	UPDATE QUESTIONARY
		SET TEMPLATE_ID = P_nTEMPLATE_ID,
			DATE_BEG = P_dDATE_BEG,
			DATE_END = P_dDATE_END
		WHERE ID = P_nID;
END pUPDATE_Q_QUESTIONARY;

-- Delete Questionary
PROCEDURE pDELETE_Q_QUESTIONARY(P_nID IN NUMBER)
IS
BEGIN
	DELETE
		FROM QUESTIONARY
		WHERE ID = P_nID;
END pDELETE_Q_QUESTIONARY;

END PKG_QUESTIONARY;