CREATE OR REPLACE PACKAGE BODY PKG$QUESTIONARY
AS

-- Create Questionary Template
PROCEDURE pCREATE_QUESTIONARY_TEMPLATE(P_vNAME IN VARCHAR2)
IS
BEGIN
	INSERT INTO QUESTIONARY_TEMPLATE
				(NAME)
		VALUES (P_vNAME);
END pCREATE_QUESTIONARY_TEMPLATE;

-- Update Questionary Template
PROCEDURE pUPDATE_QUESTIONARY_TEMPLATE(P_nID 	IN NUMBER,
										P_vNAME IN VARCHAR2)
IS 
BEGIN
	UPDATE QUESTIONARY_TEMPLATE 
		SET NAME = P_vNAME
		WHERE ID = P_nID;
END pUPDATE_QUESTIONARY_TEMPLATE;

-- Delete Questionary Template
PROCEDURE pDELETE_QUESTIONARY_TEMPLATE(P_nID IN NUMBER)
IS
BEGIN
	DELETE 
		FROM QUESTIONARY_TEMPLATE
		WHERE ID = P_nID;
END pDELETE_QUESTIONARY_TEMPLATE;

-- Create Questionary Answer Type
PROCEDURE pCREATE_Q_ANSWER_TYPE(P_vNAME IN VARCHAR2)
IS
BEGIN
	INSERT INTO QUESTIONARY_ANSWER_TYPE
				(NAME)
		VALUES (P_vNAME);
END pCREATE_Q_ANSWER_TYPE;

-- Update Questionary Answer Type
PROCEDURE pUPDATE_Q_ANSWER_TYPE(P_nID 	IN NUMBER,
								P_vNAME IN VARCHAR2)
IS 
BEGIN
	UPDATE QUESTIONARY_ANSWER_TYPE 
		SET NAME = P_vNAME
		WHERE ID = P_nID;
END pUPDATE_Q_ANSWER_TYPE;

-- Delete Questionary Answer Type
PROCEDURE pDELETE_Q_ANSWER_TYPE(P_nID IN NUMBER)
IS
BEGIN
	DELETE 
		FROM QUESTIONARY_ANSWER_TYPE
		WHERE ID = P_nID;
END pDELETE_Q_ANSWER_TYPE;

-- Create Questionary Question
PROCEDURE pCREATE_Q_QUESTION(P_nTEMPLATE_ID 	IN NUMBER,
							P_vQUESTION 		IN VARCHAR2,
							P_nANSWER_TYPE_ID	IN NUMBER)
IS
BEGIN
	INSERT INTO QUESTIONARY_QUESTION
				(TEMPLATE_ID,
				QUESTION,
				ANSWER_TYPE_ID)
		VALUES (P_nTEMPLATE_ID,
				P_vQUESTION,
				P_nANSWER_TYPE_ID);
END pCREATE_Q_QUESTION;

-- Update Questionary Question
PROCEDURE pUPDATE_Q_QUESTION(P_nID 				IN NUMBER,
							P_nTEMPLATE_ID 		IN NUMBER,
							P_vQUESTION 		IN VARCHAR2,
							P_nANSWER_TYPE_ID	IN NUMBER)
IS 
BEGIN
	UPDATE QUESTIONARY_QUESTION 
		SET TEMPLATE_ID = P_nTEMPLATE_ID,
			QUESTION = P_vQUESTION,
			ANSWER_TYPE_ID = P_nANSWER_TYPE_ID
		WHERE ID = P_nID;
END pUPDATE_Q_QUESTION;

-- Delete Questionary Answer Type
PROCEDURE pDELETE_Q_QUESTION(P_nID IN NUMBER)
IS
BEGIN
	DELETE 
		FROM QUESTIONARY_QUESTION
		WHERE ID = P_nID;
END pDELETE_Q_QUESTION;

END PKG$QUESTIONARY;