BEGIN
	PKG$QUESTIONARY.pCREATE_Q_ANSWER_TYPE('String');

	PKG$QUESTIONARY.pCREATE_Q_ANSWER_TYPE('Number');

	PKG$QUESTIONARY.pCREATE_Q_ANSWER_TYPE('Date');

	PKG$QUESTIONARY.pCREATE_Q_ANSWER_TYPE('Blob');
END;