BEGIN
	PKG_QUESTIONARY.pCREATE_Q_ANSWER_TYPE('String');
	PKG_QUESTIONARY.pCREATE_Q_ANSWER_TYPE('Number');
	PKG_QUESTIONARY.pCREATE_Q_ANSWER_TYPE('Date');
	PKG_QUESTIONARY.pCREATE_Q_ANSWER_TYPE('Blob');
	PKG_QUESTIONARY.pCREATE_Q_ANSWER_TYPE('Clob');
END;